/**
 * Tài nguyên từ các nguồn miễn phí/OER khác. Chỉ lưu metadata + liên kết tới trang gốc.
 * Các bản ghi không phải PhET được seed với isVerified = false để admin kiểm tra
 * lại liên kết trước khi gắn huy hiệu "Đã xác minh".
 */
export interface SeedSimulation {
  title: string;
  subject: string;
  gradeMin: number;
  gradeMax: number;
  topic: string;
  subtopic?: string;
  type: "virtual_lab" | "simulation" | "experiment" | "model" | "data_lab" | "game";
  source: string;
  simulationUrl: string;
  sourceUrl?: string;
  thumbnailUrl?: string;
  language: string;
  license: string;
  licenseUrl?: string;
  licenseCategory: "free" | "oer" | "creative_commons" | "external_free" | "paid";
  isFree: boolean;
  difficulty: "beginner" | "intermediate" | "advanced";
  duration: number;
  tags: string[];
  description: string;
  objectives?: string[];
  equipment?: string[];
}

const PROVIDER_TERMS = "Free educational use (see provider terms)";

export const OTHER_SIMULATIONS: SeedSimulation[] = [
  // ---- ChemCollective ----
  {
    title: "ChemCollective Virtual Lab",
    subject: "chemistry",
    gradeMin: 10,
    gradeMax: 12,
    topic: "Thí nghiệm hóa học",
    subtopic: "Phòng thí nghiệm ảo",
    type: "virtual_lab",
    source: "ChemCollective",
    simulationUrl: "https://chemcollective.org/vlab/vlab.php",
    sourceUrl: "https://chemcollective.org/vlabs",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 45,
    tags: ["phòng thí nghiệm ảo", "virtual lab", "chuẩn độ", "titration", "dung dịch", "hóa chất"],
    description:
      "Phòng thí nghiệm hóa học ảo cho phép chọn hóa chất, dụng cụ thủy tinh và thực hiện pha chế, chuẩn độ như trong phòng thí nghiệm thật.",
    equipment: ["Máy tính có trình duyệt web"],
  },
  {
    title: "ChemCollective Virtual Lab Problems",
    subject: "chemistry",
    gradeMin: 10,
    gradeMax: 12,
    topic: "Thí nghiệm hóa học",
    subtopic: "Bài tập thực hành",
    type: "virtual_lab",
    source: "ChemCollective",
    simulationUrl: "https://chemcollective.org/vlabs",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 45,
    tags: ["bài tập hóa học", "stoichiometry", "hóa học lượng", "cân bằng hóa học", "nhiệt hóa học"],
    description:
      "Bộ bài tập thực hành trong phòng thí nghiệm ảo theo chủ đề: hóa học lượng, cân bằng, axit – bazơ, nhiệt hóa học, điện hóa.",
  },
  {
    title: "ChemCollective Tutorials",
    subject: "chemistry",
    gradeMin: 10,
    gradeMax: 12,
    topic: "Hóa học đại cương",
    type: "simulation",
    source: "ChemCollective",
    simulationUrl: "https://chemcollective.org/tutorials",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 30,
    tags: ["hướng dẫn", "tutorial", "hóa học", "tự học"],
    description: "Các bài hướng dẫn tương tác giúp học sinh luyện kỹ năng giải bài tập hóa học từng bước.",
  },
  // ---- Concord Consortium ----
  {
    title: "Next-Generation Molecular Workbench",
    subject: "chemistry",
    gradeMin: 8,
    gradeMax: 12,
    topic: "Mô hình phân tử",
    subtopic: "Động học phân tử",
    type: "model",
    source: "Concord Consortium",
    simulationUrl: "https://mw.concord.org/nextgen/",
    language: "en",
    license: "Open educational resource (see provider terms)",
    licenseCategory: "oer",
    isFree: true,
    difficulty: "intermediate",
    duration: 30,
    tags: ["molecular workbench", "phân tử", "mô hình", "liên kết", "trạng thái chất", "nhiệt"],
    description:
      "Bộ mô hình tương tác ở cấp độ nguyên tử – phân tử về trạng thái chất, liên kết hóa học, nhiệt và khuếch tán.",
  },
  {
    title: "Energy2D",
    subject: "physics",
    gradeMin: 8,
    gradeMax: 12,
    topic: "Nhiệt học",
    subtopic: "Truyền nhiệt",
    type: "simulation",
    source: "Concord Consortium",
    simulationUrl: "https://energy.concord.org/energy2d/",
    language: "en",
    license: "Open source (see provider terms)",
    licenseCategory: "oer",
    isFree: true,
    difficulty: "intermediate",
    duration: 30,
    tags: ["truyền nhiệt", "heat transfer", "dẫn nhiệt", "đối lưu", "bức xạ", "nhà tiết kiệm năng lượng"],
    description:
      "Mô phỏng truyền nhiệt bằng dẫn nhiệt, đối lưu và bức xạ; phù hợp dự án STEM thiết kế nhà tiết kiệm năng lượng.",
  },
  {
    title: "CODAP – Common Online Data Analysis Platform",
    subject: "mathematics",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Xác suất – Thống kê",
    subtopic: "Phân tích dữ liệu",
    type: "data_lab",
    source: "Concord Consortium",
    simulationUrl: "https://codap.concord.org/",
    language: "en",
    license: "Open source (see provider terms)",
    licenseCategory: "oer",
    isFree: true,
    difficulty: "beginner",
    duration: 45,
    tags: ["phân tích dữ liệu", "data analysis", "thống kê", "biểu đồ", "graph", "data science"],
    description:
      "Công cụ phân tích dữ liệu trực tuyến dành cho học sinh: kéo thả dữ liệu, vẽ biểu đồ, bản đồ và tìm quy luật.",
  },
  // ---- LabXchange ----
  {
    title: "LabXchange Library",
    subject: "biology",
    gradeMin: 9,
    gradeMax: 12,
    topic: "Sinh học phân tử",
    subtopic: "Phòng thí nghiệm ảo",
    type: "virtual_lab",
    source: "LabXchange",
    simulationUrl: "https://www.labxchange.org/library",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 45,
    tags: ["labxchange", "sinh học phân tử", "pcr", "điện di", "gel electrophoresis", "virtual lab"],
    description:
      "Thư viện nội dung khoa học miễn phí, trong đó có các phòng thí nghiệm ảo về kỹ thuật sinh học phân tử như PCR, điện di.",
  },
  // ---- NOVA Labs ----
  {
    title: "NOVA Evolution Lab",
    subject: "biology",
    gradeMin: 8,
    gradeMax: 12,
    topic: "Tiến hóa",
    subtopic: "Cây phát sinh chủng loại",
    type: "game",
    source: "NOVA Labs",
    simulationUrl: "https://www.pbs.org/wgbh/nova/labs/lab/evolution/",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 45,
    tags: ["tiến hóa", "evolution", "cây phát sinh", "phylogeny", "dna"],
    description:
      "Xây dựng cây phát sinh chủng loại dựa trên đặc điểm hình thái và bằng chứng DNA qua các nhiệm vụ dạng trò chơi.",
  },
  {
    title: "NOVA RNA Lab",
    subject: "biology",
    gradeMin: 9,
    gradeMax: 12,
    topic: "Di truyền",
    subtopic: "RNA",
    type: "game",
    source: "NOVA Labs",
    simulationUrl: "https://www.pbs.org/wgbh/nova/labs/lab/rna/",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "advanced",
    duration: 30,
    tags: ["rna", "gấp cuộn rna", "phân tử sinh học", "di truyền"],
    description: "Giải các câu đố gấp cuộn phân tử RNA để hiểu cấu trúc và chức năng của RNA.",
  },
  {
    title: "NOVA Energy Lab",
    subject: "environmental-science",
    gradeMin: 8,
    gradeMax: 12,
    topic: "Năng lượng tái tạo",
    type: "data_lab",
    source: "NOVA Labs",
    simulationUrl: "https://www.pbs.org/wgbh/nova/labs/lab/energy/",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 45,
    tags: ["năng lượng tái tạo", "renewable energy", "điện mặt trời", "điện gió", "dữ liệu"],
    description:
      "Phân tích dữ liệu thực và thiết kế hệ thống năng lượng tái tạo (mặt trời, gió) cho các địa điểm khác nhau.",
  },
  {
    title: "NOVA Sun Lab",
    subject: "earth-science",
    gradeMin: 8,
    gradeMax: 12,
    topic: "Thiên văn",
    subtopic: "Mặt Trời",
    type: "data_lab",
    source: "NOVA Labs",
    simulationUrl: "https://www.pbs.org/wgbh/nova/labs/lab/sun/",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 30,
    tags: ["mặt trời", "sun", "thời tiết không gian", "vết đen mặt trời", "thiên văn"],
    description: "Khám phá hình ảnh Mặt Trời từ vệ tinh và dự báo các hiện tượng thời tiết không gian.",
  },
  {
    title: "NOVA Cloud Lab",
    subject: "earth-science",
    gradeMin: 6,
    gradeMax: 10,
    topic: "Khí tượng",
    subtopic: "Mây và bão",
    type: "data_lab",
    source: "NOVA Labs",
    simulationUrl: "https://www.pbs.org/wgbh/nova/labs/lab/cloud/",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 30,
    tags: ["mây", "cloud", "thời tiết", "weather", "bão", "khí tượng"],
    description:
      "Phân loại các loại mây và tìm hiểu vai trò của mây trong hình thành bão qua dữ liệu vệ tinh.",
  },
  {
    title: "NOVA Cybersecurity Lab",
    subject: "computer-science",
    gradeMin: 7,
    gradeMax: 12,
    topic: "An toàn thông tin",
    type: "game",
    source: "NOVA Labs",
    simulationUrl: "https://www.pbs.org/wgbh/nova/labs/lab/cyber/",
    language: "en",
    license: PROVIDER_TERMS,
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 30,
    tags: ["an toàn thông tin", "cybersecurity", "mật khẩu", "mã hóa", "tin học"],
    description:
      "Trò chơi bảo vệ công ty khởi nghiệp trước tấn công mạng, học về mật khẩu mạnh, lừa đảo và mã hóa.",
  },
  // ---- Toán học ----
  {
    title: "Desmos Graphing Calculator",
    subject: "mathematics",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Hàm số",
    subtopic: "Đồ thị",
    type: "simulation",
    source: "Desmos",
    simulationUrl: "https://www.desmos.com/calculator",
    language: "multi",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 20,
    tags: ["máy tính đồ thị", "graphing calculator", "đồ thị", "hàm số", "tham số", "slider"],
    description:
      "Máy tính đồ thị trực tuyến: vẽ hàm số, bất phương trình, dữ liệu và dùng thanh trượt tham số để khám phá.",
  },
  {
    title: "Desmos Geometry",
    subject: "mathematics",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Hình học",
    subtopic: "Dựng hình",
    type: "simulation",
    source: "Desmos",
    simulationUrl: "https://www.desmos.com/geometry",
    language: "multi",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 20,
    tags: ["hình học", "geometry", "dựng hình", "phép biến hình"],
    description: "Công cụ dựng hình học phẳng: điểm, đường, đường tròn, phép biến hình và đo đạc.",
  },
  {
    title: "Desmos Scientific Calculator",
    subject: "mathematics",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Số học",
    subtopic: "Máy tính khoa học",
    type: "simulation",
    source: "Desmos",
    simulationUrl: "https://www.desmos.com/scientific",
    language: "multi",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 5,
    tags: ["máy tính khoa học", "scientific calculator", "tính toán"],
    description: "Máy tính khoa học trực tuyến miễn phí, dễ dùng trên máy chiếu và bảng tương tác.",
  },
  {
    title: "GeoGebra Graphing Calculator",
    subject: "mathematics",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Hàm số",
    subtopic: "Đồ thị",
    type: "simulation",
    source: "GeoGebra",
    simulationUrl: "https://www.geogebra.org/graphing",
    language: "multi",
    license: "Free for non-commercial use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 20,
    tags: ["geogebra", "đồ thị", "hàm số", "graphing"],
    description: "Vẽ đồ thị hàm số, tìm giao điểm, cực trị và khảo sát hàm số trực quan.",
  },
  {
    title: "GeoGebra Geometry",
    subject: "mathematics",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Hình học",
    subtopic: "Hình học phẳng",
    type: "simulation",
    source: "GeoGebra",
    simulationUrl: "https://www.geogebra.org/geometry",
    language: "multi",
    license: "Free for non-commercial use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 20,
    tags: ["geogebra", "hình học phẳng", "dựng hình", "tam giác", "đường tròn"],
    description:
      "Dựng hình học phẳng động: tam giác, đường tròn, đường trung trực, phân giác và kiểm chứng tính chất.",
  },
  {
    title: "GeoGebra 3D Calculator",
    subject: "mathematics",
    gradeMin: 9,
    gradeMax: 12,
    topic: "Hình học",
    subtopic: "Hình học không gian",
    type: "simulation",
    source: "GeoGebra",
    simulationUrl: "https://www.geogebra.org/3d",
    language: "multi",
    license: "Free for non-commercial use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 30,
    tags: ["hình học không gian", "3d", "khối đa diện", "mặt phẳng", "geogebra"],
    description: "Vẽ và xoay các hình khối, mặt phẳng, mặt cong trong không gian ba chiều.",
  },
  // ---- Khoa học Trái đất / Thiên văn ----
  {
    title: "Stellarium Web Planetarium",
    subject: "earth-science",
    gradeMin: 4,
    gradeMax: 12,
    topic: "Thiên văn",
    subtopic: "Bầu trời sao",
    type: "simulation",
    source: "Stellarium Web",
    simulationUrl: "https://stellarium-web.org/",
    language: "multi",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 20,
    tags: ["thiên văn", "astronomy", "bầu trời", "chòm sao", "planetarium", "sao"],
    description:
      "Cung thiên văn trực tuyến hiển thị bầu trời tại vị trí và thời điểm bất kỳ, tìm chòm sao và hành tinh.",
  },
  {
    title: "NASA's Eyes on the Solar System",
    subject: "earth-science",
    gradeMin: 5,
    gradeMax: 12,
    topic: "Thiên văn",
    subtopic: "Hệ Mặt Trời",
    type: "model",
    source: "NASA",
    simulationUrl: "https://eyes.nasa.gov/apps/solar-system/",
    language: "en",
    license: "NASA media usage guidelines",
    licenseCategory: "free",
    isFree: true,
    difficulty: "beginner",
    duration: 30,
    tags: ["hệ mặt trời", "solar system", "tàu vũ trụ", "hành tinh", "nasa", "3d"],
    description:
      "Khám phá Hệ Mặt Trời 3D theo thời gian thực với vị trí hành tinh, tiểu hành tinh và tàu vũ trụ dựa trên dữ liệu NASA.",
  },
  {
    title: "NASA's Eyes on the Earth",
    subject: "earth-science",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Trái Đất",
    subtopic: "Vệ tinh quan sát",
    type: "data_lab",
    source: "NASA",
    simulationUrl: "https://eyes.nasa.gov/apps/earth/",
    language: "en",
    license: "NASA media usage guidelines",
    licenseCategory: "free",
    isFree: true,
    difficulty: "intermediate",
    duration: 30,
    tags: ["trái đất", "earth", "vệ tinh", "nhiệt độ", "khí hậu", "dữ liệu"],
    description:
      "Theo dõi các vệ tinh quan sát Trái Đất và xem dữ liệu về nhiệt độ, CO₂, mực nước biển, băng.",
  },
  {
    title: "NASA's Eyes on Exoplanets",
    subject: "earth-science",
    gradeMin: 8,
    gradeMax: 12,
    topic: "Thiên văn",
    subtopic: "Ngoại hành tinh",
    type: "model",
    source: "NASA",
    simulationUrl: "https://eyes.nasa.gov/apps/exo/",
    language: "en",
    license: "NASA media usage guidelines",
    licenseCategory: "free",
    isFree: true,
    difficulty: "intermediate",
    duration: 20,
    tags: ["ngoại hành tinh", "exoplanet", "thiên văn", "nasa"],
    description: "Khám phá hàng nghìn ngoại hành tinh đã được phát hiện trong mô hình 3D của Ngân Hà.",
  },
  {
    title: "USGS Latest Earthquakes Map",
    subject: "earth-science",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Địa chất",
    subtopic: "Động đất",
    type: "data_lab",
    source: "USGS",
    simulationUrl: "https://earthquake.usgs.gov/earthquakes/map/",
    language: "en",
    license: "Public domain (U.S. Government work)",
    licenseCategory: "free",
    isFree: true,
    difficulty: "beginner",
    duration: 20,
    tags: ["động đất", "earthquake", "mảng kiến tạo", "địa chấn", "bản đồ"],
    description:
      "Bản đồ động đất trên toàn cầu gần thời gian thực, dùng để tìm quy luật phân bố theo ranh giới mảng kiến tạo.",
  },
  {
    title: "earth.nullschool – Global Wind & Weather Map",
    subject: "earth-science",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Khí tượng",
    subtopic: "Gió và hải lưu",
    type: "data_lab",
    source: "earth.nullschool",
    simulationUrl: "https://earth.nullschool.net/",
    language: "en",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 15,
    tags: ["gió", "wind", "hải lưu", "ocean currents", "bão", "khí quyển", "thời tiết"],
    description:
      "Trực quan hóa gió, hải lưu, nhiệt độ và chất lượng không khí toàn cầu trên quả địa cầu tương tác.",
  },
  {
    title: "Global Forest Watch Map",
    subject: "environmental-science",
    gradeMin: 7,
    gradeMax: 12,
    topic: "Tài nguyên rừng",
    subtopic: "Mất rừng",
    type: "data_lab",
    source: "Global Forest Watch",
    simulationUrl: "https://www.globalforestwatch.org/map/",
    language: "multi",
    license: "Free to use; data mostly CC BY 4.0 (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 30,
    tags: ["rừng", "forest", "mất rừng", "deforestation", "cháy rừng", "bản đồ", "môi trường"],
    description:
      "Bản đồ dữ liệu mở về độ che phủ rừng, mất rừng và cháy rừng; có thể xem theo từng quốc gia, kể cả Việt Nam.",
  },
  // ---- Tin học ----
  {
    title: "Scratch Online Editor",
    subject: "computer-science",
    gradeMin: 3,
    gradeMax: 9,
    topic: "Lập trình",
    subtopic: "Lập trình khối",
    type: "simulation",
    source: "Scratch",
    simulationUrl: "https://scratch.mit.edu/projects/editor/",
    language: "multi",
    license: "Free to use; community projects CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 45,
    tags: ["lập trình", "programming", "scratch", "khối lệnh", "trò chơi", "hoạt hình"],
    description:
      "Trình soạn thảo lập trình khối trực tuyến để tạo truyện tương tác, trò chơi và hoạt hình; có giao diện tiếng Việt.",
  },
  {
    title: "Blockly Games",
    subject: "computer-science",
    gradeMin: 3,
    gradeMax: 9,
    topic: "Lập trình",
    subtopic: "Tư duy thuật toán",
    type: "game",
    source: "Blockly Games",
    simulationUrl: "https://blockly.games/",
    language: "multi",
    license: "Apache License 2.0",
    licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0",
    licenseCategory: "oer",
    isFree: true,
    difficulty: "beginner",
    duration: 30,
    tags: ["lập trình", "vòng lặp", "điều kiện", "thuật toán", "blockly", "trò chơi"],
    description:
      "Chuỗi trò chơi giải đố giúp học vòng lặp, điều kiện, biến và chuyển dần từ khối lệnh sang JavaScript.",
  },
  // ---- Vật lý / Điện tử (Falstad) ----
  {
    title: "CircuitJS – Falstad Circuit Simulator",
    subject: "physics",
    gradeMin: 10,
    gradeMax: 12,
    topic: "Điện học",
    subtopic: "Mạch điện tử",
    type: "simulation",
    source: "Falstad",
    simulationUrl: "https://www.falstad.com/circuit/circuitjs.html",
    language: "en",
    license: "GPL (see provider terms)",
    licenseCategory: "oer",
    isFree: true,
    difficulty: "advanced",
    duration: 45,
    tags: ["mạch điện tử", "electronics", "circuit", "transistor", "diode", "tụ điện", "dao động ký"],
    description:
      "Trình mô phỏng mạch điện tử trực quan với dòng electron chuyển động, hỗ trợ transistor, diode, cổng logic.",
  },
  {
    title: "Ripple Tank Simulation",
    subject: "physics",
    gradeMin: 10,
    gradeMax: 12,
    topic: "Sóng",
    subtopic: "Giao thoa – nhiễu xạ",
    type: "simulation",
    source: "Falstad",
    simulationUrl: "https://www.falstad.com/ripple/",
    language: "en",
    license: "GPL (see provider terms)",
    licenseCategory: "oer",
    isFree: true,
    difficulty: "intermediate",
    duration: 20,
    tags: ["chậu sóng", "ripple tank", "giao thoa", "nhiễu xạ", "hiệu ứng doppler"],
    description:
      "Mô phỏng chậu sóng 2D: giao thoa, nhiễu xạ, khúc xạ, hiệu ứng Doppler với nhiều cấu hình nguồn sóng.",
  },
  // ---- Hóa học ----
  {
    title: "MolView",
    subject: "chemistry",
    gradeMin: 9,
    gradeMax: 12,
    topic: "Cấu trúc phân tử",
    subtopic: "Mô hình 3D",
    type: "model",
    source: "MolView",
    simulationUrl: "https://molview.org/",
    language: "en",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "intermediate",
    duration: 15,
    tags: ["phân tử 3d", "molecule", "cấu trúc", "hữu cơ", "protein", "tinh thể"],
    description:
      "Vẽ công thức cấu tạo 2D và xem mô hình 3D của phân tử, protein và tinh thể ngay trên trình duyệt.",
  },
  // ---- STEM / Âm thanh ----
  {
    title: "Chrome Music Lab: Spectrogram",
    subject: "stem",
    gradeMin: 3,
    gradeMax: 12,
    topic: "Âm thanh",
    subtopic: "Phổ âm",
    type: "experiment",
    source: "Chrome Music Lab",
    simulationUrl: "https://musiclab.chromeexperiments.com/Spectrogram/",
    language: "multi",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 15,
    tags: ["âm thanh", "sound", "phổ âm", "tần số", "spectrogram", "micro"],
    description:
      "Hiển thị phổ tần số của âm thanh theo thời gian; có thể dùng micro để phân tích giọng nói và nhạc cụ.",
    equipment: ["Micro (không bắt buộc)"],
  },
  {
    title: "Chrome Music Lab: Oscillators",
    subject: "stem",
    gradeMin: 3,
    gradeMax: 9,
    topic: "Âm thanh",
    subtopic: "Dao động và âm sắc",
    type: "experiment",
    source: "Chrome Music Lab",
    simulationUrl: "https://musiclab.chromeexperiments.com/Oscillators/",
    language: "multi",
    license: "Free to use (see provider terms)",
    licenseCategory: "external_free",
    isFree: true,
    difficulty: "beginner",
    duration: 10,
    tags: ["dao động", "oscillator", "âm thanh", "tần số", "dạng sóng"],
    description:
      "Nghe và so sánh các dạng sóng cơ bản (sin, vuông, tam giác, răng cưa) ở những tần số khác nhau.",
    equipment: ["Loa hoặc tai nghe"],
  },
  {
    title: "Yenka Science & Technology",
    subject: "stem",
    gradeMin: 6,
    gradeMax: 12,
    topic: "Mô phỏng STEM",
    subtopic: "Điện tử, hóa học, quang học",
    type: "virtual_lab",
    source: "Yenka",
    simulationUrl: "https://www.yenka.com/",
    language: "en",
    license: "Commercial (free home licence available)",
    licenseCategory: "paid",
    isFree: false,
    difficulty: "intermediate",
    duration: 45,
    tags: ["yenka", "phòng thí nghiệm ảo", "điện tử", "hóa học", "quang học", "phần mềm"],
    description:
      "Phần mềm mô phỏng cài đặt trên máy tính cho điện tử, hóa học, quang học và toán học; trường học cần mua bản quyền.",
    equipment: ["Máy tính Windows/macOS cài đặt phần mềm"],
  },
];

/** Mục tiêu học tập cho các mô phỏng PhET phổ biến (theo slug). */
export const PHET_OBJECTIVES: Record<string, string[]> = {
  "circuit-construction-kit-dc": [
    "Lắp được mạch điện nối tiếp và song song từ sơ đồ cho trước.",
    "Dùng ampe kế, vôn kế ảo để đo cường độ dòng điện và hiệu điện thế.",
    "So sánh độ sáng bóng đèn trong mạch nối tiếp và song song.",
  ],
  "ohms-law": [
    "Phát biểu được định luật Ohm U = I·R.",
    "Dự đoán sự thay đổi cường độ dòng điện khi thay đổi U hoặc R.",
  ],
  "forces-and-motion-basics": [
    "Nhận biết lực cân bằng và lực không cân bằng.",
    "Giải thích ảnh hưởng của ma sát và khối lượng đến chuyển động.",
  ],
  "projectile-motion": [
    "Xác định ảnh hưởng của góc bắn và vận tốc ban đầu đến tầm xa.",
    "Phân tích chuyển động ném thành hai chuyển động thành phần.",
    "Nhận xét vai trò của sức cản không khí.",
  ],
  "pendulum-lab": [
    "Xác định các yếu tố ảnh hưởng đến chu kỳ con lắc đơn.",
    "Dùng con lắc để xác định gia tốc trọng trường.",
  ],
  "energy-skate-park-basics": [
    "Mô tả sự chuyển hóa giữa động năng và thế năng.",
    "Giải thích vì sao cơ năng giảm khi có ma sát.",
  ],
  "build-an-atom": ["Xác định nguyên tố dựa vào số proton.", "Tính số khối và điện tích của nguyên tử/ion."],
  "balancing-chemical-equations": [
    "Cân bằng được phương trình hóa học đơn giản.",
    "Giải thích định luật bảo toàn khối lượng ở cấp độ nguyên tử.",
  ],
  "ph-scale": [
    "Phân loại dung dịch axit, bazơ, trung tính dựa trên pH.",
    "Dự đoán sự thay đổi pH khi pha loãng dung dịch.",
  ],
  "states-of-matter": [
    "Mô tả chuyển động của phân tử ở ba thể rắn, lỏng, khí.",
    "Giải thích sự chuyển thể khi thay đổi nhiệt độ và áp suất.",
  ],
  "natural-selection": [
    "Giải thích cơ chế chọn lọc tự nhiên dựa trên dữ liệu quần thể.",
    "Phân tích ảnh hưởng của đột biến và yếu tố môi trường.",
  ],
  "greenhouse-effect": [
    "Mô tả cách khí nhà kính hấp thụ và phát xạ bức xạ hồng ngoại.",
    "Liên hệ nồng độ khí nhà kính với nhiệt độ Trái Đất.",
  ],
  "fractions-intro": [
    "Biểu diễn phân số bằng nhiều mô hình khác nhau.",
    "Liên hệ phân số với vị trí trên trục số.",
  ],
  "graphing-quadratics": [
    "Xác định đỉnh, trục đối xứng và nghiệm của parabol.",
    "Giải thích ảnh hưởng của các hệ số a, b, c đến đồ thị.",
  ],
  "bending-light": [
    "Vận dụng định luật Snell để dự đoán góc khúc xạ.",
    "Xác định điều kiện xảy ra phản xạ toàn phần.",
  ],
  "gas-properties": [
    "Mô tả mối quan hệ giữa p, V, T của chất khí.",
    "Giải thích áp suất chất khí bằng mô hình động học phân tử.",
  ],
  "wave-on-a-string": [
    "Phân biệt biên độ, tần số, bước sóng.",
    "Mô tả điều kiện hình thành sóng dừng trên dây.",
  ],
  "gravity-and-orbits": [
    "Giải thích vai trò của lực hấp dẫn trong chuyển động quỹ đạo.",
    "Dự đoán điều gì xảy ra với quỹ đạo khi thay đổi khối lượng.",
  ],
};
