/**
 * Mô phỏng HTML5 của PhET Interactive Simulations (CC BY 4.0).
 * Chỉ lưu metadata + liên kết. Mô tả tiếng Việt do dự án tự biên soạn, không sao chép từ PhET.
 *
 * [slug, title, subject, gradeMin, gradeMax, topic, subtopic, type, durationMin, difficulty, tags, description]
 */
export type PhetRow = [
  slug: string,
  title: string,
  subject: string,
  gradeMin: number,
  gradeMax: number,
  topic: string,
  subtopic: string | null,
  type: "simulation" | "virtual_lab" | "game" | "model",
  duration: number,
  difficulty: "beginner" | "intermediate" | "advanced",
  tags: string[],
  description: string,
];

export const PHET_SIMULATIONS: PhetRow[] = [
  // ------------------------------- VẬT LÝ – ĐIỆN -------------------------------
  [
    "circuit-construction-kit-dc",
    "Circuit Construction Kit: DC",
    "physics",
    7,
    12,
    "Điện học",
    "Mạch điện một chiều",
    "simulation",
    45,
    "intermediate",
    ["mạch điện", "circuit", "điện trở", "resistance", "voltage", "current", "ohm", "ampe kế", "vôn kế"],
    "Lắp mạch điện một chiều với pin, bóng đèn, điện trở và công tắc; đo hiệu điện thế và cường độ dòng điện bằng dụng cụ ảo.",
  ],
  [
    "circuit-construction-kit-dc-virtual-lab",
    "Circuit Construction Kit: DC – Virtual Lab",
    "physics",
    9,
    12,
    "Điện học",
    "Mạch điện một chiều",
    "virtual_lab",
    45,
    "intermediate",
    ["mạch điện", "circuit", "virtual lab", "điện trở trong", "internal resistance", "ohm"],
    "Phiên bản phòng thí nghiệm ảo của bộ lắp mạch điện DC, cho phép thay đổi điện trở trong của nguồn và điện trở suất của dây.",
  ],
  [
    "circuit-construction-kit-ac",
    "Circuit Construction Kit: AC",
    "physics",
    10,
    12,
    "Điện học",
    "Dòng điện xoay chiều",
    "simulation",
    45,
    "advanced",
    [
      "dòng điện xoay chiều",
      "alternating current",
      "tụ điện",
      "capacitor",
      "cuộn cảm",
      "inductor",
      "circuit",
    ],
    "Khảo sát mạch điện xoay chiều có tụ điện, cuộn cảm và điện trở; quan sát dòng điện, hiệu điện thế thay đổi theo thời gian.",
  ],
  [
    "circuit-construction-kit-ac-virtual-lab",
    "Circuit Construction Kit: AC – Virtual Lab",
    "physics",
    11,
    12,
    "Điện học",
    "Dòng điện xoay chiều",
    "virtual_lab",
    45,
    "advanced",
    ["dòng điện xoay chiều", "ac circuit", "virtual lab", "capacitor", "inductor"],
    "Phòng thí nghiệm ảo về mạch xoay chiều với các thông số linh kiện có thể điều chỉnh chi tiết.",
  ],
  [
    "ohms-law",
    "Ohm's Law",
    "physics",
    7,
    11,
    "Điện học",
    "Định luật Ohm",
    "simulation",
    15,
    "beginner",
    [
      "định luật ohm",
      "ohm",
      "điện trở",
      "hiệu điện thế",
      "cường độ dòng điện",
      "voltage",
      "current",
      "resistance",
    ],
    "Trực quan hóa mối liên hệ U = I·R: thay đổi hiệu điện thế và điện trở để thấy cường độ dòng điện thay đổi như thế nào.",
  ],
  [
    "resistance-in-a-wire",
    "Resistance in a Wire",
    "physics",
    8,
    11,
    "Điện học",
    "Điện trở của dây dẫn",
    "simulation",
    15,
    "beginner",
    ["điện trở", "điện trở suất", "resistivity", "dây dẫn", "resistance"],
    "Khám phá điện trở của dây dẫn phụ thuộc vào điện trở suất, chiều dài và tiết diện của dây.",
  ],
  [
    "capacitor-lab-basics",
    "Capacitor Lab: Basics",
    "physics",
    10,
    12,
    "Điện học",
    "Tụ điện",
    "simulation",
    30,
    "intermediate",
    ["tụ điện", "capacitor", "điện dung", "capacitance", "điện trường"],
    "Tìm hiểu điện dung của tụ điện phẳng phụ thuộc vào diện tích bản và khoảng cách giữa hai bản; quan sát điện tích và năng lượng tích trữ.",
  ],
  [
    "charges-and-fields",
    "Charges and Fields",
    "physics",
    10,
    12,
    "Điện học",
    "Điện trường",
    "simulation",
    30,
    "intermediate",
    ["điện trường", "electric field", "điện tích", "charge", "điện thế", "equipotential"],
    "Đặt các điện tích điểm và quan sát điện trường, điện thế và các đường đẳng thế xung quanh chúng.",
  ],
  [
    "coulombs-law",
    "Coulomb's Law",
    "physics",
    10,
    12,
    "Điện học",
    "Định luật Coulomb",
    "simulation",
    20,
    "intermediate",
    ["định luật coulomb", "coulomb", "lực điện", "electric force", "điện tích"],
    "Đo lực tương tác giữa hai điện tích điểm và khám phá sự phụ thuộc vào độ lớn điện tích và khoảng cách.",
  ],
  [
    "balloons-and-static-electricity",
    "Balloons and Static Electricity",
    "physics",
    3,
    9,
    "Điện học",
    "Tĩnh điện",
    "simulation",
    20,
    "beginner",
    ["tĩnh điện", "static electricity", "bóng bay", "balloon", "điện tích", "nhiễm điện"],
    "Cọ xát quả bóng bay vào áo len để quan sát sự dịch chuyển điện tích và hiện tượng hút – đẩy do tĩnh điện.",
  ],
  [
    "john-travoltage",
    "John Travoltage",
    "physics",
    3,
    9,
    "Điện học",
    "Tĩnh điện",
    "simulation",
    10,
    "beginner",
    ["tĩnh điện", "static electricity", "phóng điện", "discharge", "điện tích"],
    "Tích điện cho nhân vật bằng cách cọ chân lên thảm rồi quan sát tia lửa điện khi tay chạm vào nắm cửa.",
  ],
  [
    "faradays-law",
    "Faraday's Law",
    "physics",
    9,
    12,
    "Điện từ học",
    "Cảm ứng điện từ",
    "simulation",
    20,
    "intermediate",
    ["cảm ứng điện từ", "electromagnetic induction", "faraday", "nam châm", "magnet", "cuộn dây"],
    "Di chuyển nam châm qua cuộn dây để tạo ra dòng điện cảm ứng; khám phá vai trò của tốc độ và số vòng dây.",
  ],
  // ------------------------------- VẬT LÝ – CƠ HỌC -------------------------------
  [
    "forces-and-motion-basics",
    "Forces and Motion: Basics",
    "physics",
    3,
    8,
    "Cơ học",
    "Lực và chuyển động",
    "simulation",
    30,
    "beginner",
    ["lực", "force", "chuyển động", "motion", "ma sát", "friction", "định luật newton", "kéo co"],
    "Khám phá lực cân bằng và không cân bằng qua trò kéo co, đẩy vật và ảnh hưởng của ma sát lên chuyển động.",
  ],
  [
    "friction",
    "Friction",
    "physics",
    4,
    8,
    "Cơ học",
    "Ma sát",
    "simulation",
    15,
    "beginner",
    ["ma sát", "friction", "nhiệt", "heat", "phân tử"],
    "Quan sát ở cấp độ phân tử điều gì xảy ra khi hai bề mặt cọ xát vào nhau và vì sao ma sát làm vật nóng lên.",
  ],
  [
    "projectile-motion",
    "Projectile Motion",
    "physics",
    9,
    12,
    "Cơ học",
    "Chuyển động ném",
    "simulation",
    30,
    "intermediate",
    ["chuyển động ném", "ném xiên", "projectile motion", "quỹ đạo", "trajectory", "sức cản không khí"],
    "Bắn các vật thể từ khẩu pháo và khảo sát tầm xa, độ cao cực đại theo góc bắn, vận tốc đầu và sức cản không khí.",
  ],
  [
    "pendulum-lab",
    "Pendulum Lab",
    "physics",
    9,
    12,
    "Dao động",
    "Con lắc đơn",
    "virtual_lab",
    30,
    "intermediate",
    ["con lắc", "pendulum", "dao động", "chu kỳ", "period", "gia tốc trọng trường"],
    "Đo chu kỳ con lắc đơn khi thay đổi chiều dài, khối lượng, biên độ và gia tốc trọng trường (kể cả trên các hành tinh khác).",
  ],
  [
    "masses-and-springs",
    "Masses and Springs",
    "physics",
    9,
    12,
    "Dao động",
    "Con lắc lò xo",
    "simulation",
    30,
    "intermediate",
    ["lò xo", "spring", "con lắc lò xo", "dao động", "định luật hooke", "năng lượng"],
    "Treo vật nặng vào lò xo để khám phá định luật Hooke, dao động điều hòa và sự chuyển hóa năng lượng.",
  ],
  [
    "masses-and-springs-basics",
    "Masses and Springs: Basics",
    "physics",
    6,
    9,
    "Cơ học",
    "Lò xo",
    "simulation",
    20,
    "beginner",
    ["lò xo", "spring", "độ giãn", "khối lượng", "mass"],
    "Phiên bản cơ bản giúp học sinh THCS thấy độ giãn của lò xo phụ thuộc vào khối lượng vật treo và độ cứng lò xo.",
  ],
  [
    "hookes-law",
    "Hooke's Law",
    "physics",
    8,
    12,
    "Cơ học",
    "Định luật Hooke",
    "simulation",
    20,
    "intermediate",
    ["định luật hooke", "hookes law", "lò xo", "spring", "độ cứng", "lực đàn hồi"],
    "Kéo và nén lò xo để tìm mối liên hệ giữa lực tác dụng, độ biến dạng và độ cứng; ghép lò xo nối tiếp và song song.",
  ],
  [
    "energy-skate-park-basics",
    "Energy Skate Park: Basics",
    "physics",
    6,
    9,
    "Năng lượng",
    "Cơ năng",
    "simulation",
    30,
    "beginner",
    ["năng lượng", "energy", "động năng", "thế năng", "cơ năng", "bảo toàn năng lượng", "trượt ván"],
    "Quan sát sự chuyển hóa giữa động năng và thế năng của người trượt ván trên đường dốc, có và không có ma sát.",
  ],
  [
    "energy-skate-park",
    "Energy Skate Park",
    "physics",
    9,
    12,
    "Năng lượng",
    "Bảo toàn cơ năng",
    "simulation",
    45,
    "intermediate",
    ["bảo toàn năng lượng", "energy conservation", "động năng", "thế năng", "nhiệt năng", "ma sát"],
    "Thiết kế đường trượt riêng, đo năng lượng bằng biểu đồ và kiểm chứng định luật bảo toàn cơ năng.",
  ],
  [
    "gravity-and-orbits",
    "Gravity and Orbits",
    "physics",
    6,
    12,
    "Thiên văn",
    "Lực hấp dẫn",
    "simulation",
    20,
    "beginner",
    ["hấp dẫn", "gravity", "quỹ đạo", "orbit", "mặt trời", "trái đất", "mặt trăng"],
    "Điều chỉnh khối lượng và khoảng cách giữa Mặt Trời, Trái Đất, Mặt Trăng để thấy lực hấp dẫn quyết định quỹ đạo.",
  ],
  [
    "gravity-force-lab",
    "Gravity Force Lab",
    "physics",
    9,
    12,
    "Cơ học",
    "Định luật vạn vật hấp dẫn",
    "simulation",
    20,
    "intermediate",
    ["vạn vật hấp dẫn", "gravity force", "newton", "khối lượng", "khoảng cách"],
    "Đo lực hấp dẫn giữa hai vật và khám phá sự phụ thuộc vào khối lượng và khoảng cách theo định luật Newton.",
  ],
  [
    "gravity-force-lab-basics",
    "Gravity Force Lab: Basics",
    "physics",
    6,
    9,
    "Cơ học",
    "Lực hấp dẫn",
    "simulation",
    15,
    "beginner",
    ["hấp dẫn", "gravity", "khối lượng", "mass", "khoảng cách"],
    "Phiên bản cơ bản giúp nhận biết lực hấp dẫn tăng khi khối lượng tăng và giảm khi khoảng cách tăng.",
  ],
  [
    "keplers-laws",
    "Kepler's Laws",
    "physics",
    10,
    12,
    "Thiên văn",
    "Định luật Kepler",
    "simulation",
    30,
    "advanced",
    ["định luật kepler", "kepler", "quỹ đạo elip", "orbit", "hành tinh"],
    "Khám phá ba định luật Kepler: quỹ đạo elip, diện tích quét bằng nhau và mối liên hệ giữa chu kỳ và bán trục lớn.",
  ],
  [
    "my-solar-system",
    "My Solar System",
    "physics",
    9,
    12,
    "Thiên văn",
    "Hệ hấp dẫn nhiều vật",
    "simulation",
    30,
    "intermediate",
    ["hệ mặt trời", "solar system", "quỹ đạo", "orbit", "hấp dẫn", "hành tinh"],
    "Tạo hệ gồm nhiều thiên thể, đặt vận tốc ban đầu và quan sát các quỹ đạo ổn định hoặc hỗn loạn.",
  ],
  [
    "balancing-act",
    "Balancing Act",
    "physics",
    5,
    9,
    "Cơ học",
    "Cân bằng – Momen lực",
    "simulation",
    20,
    "beginner",
    ["cân bằng", "balance", "đòn bẩy", "momen lực", "torque"],
    "Đặt vật nặng lên bập bênh để khám phá điều kiện cân bằng của đòn bẩy; có chế độ trò chơi thử thách.",
  ],
  [
    "collision-lab",
    "Collision Lab",
    "physics",
    10,
    12,
    "Cơ học",
    "Động lượng và va chạm",
    "simulation",
    30,
    "advanced",
    ["va chạm", "collision", "động lượng", "momentum", "đàn hồi", "elastic"],
    "Khảo sát va chạm đàn hồi và không đàn hồi trong 1D và 2D, kiểm chứng định luật bảo toàn động lượng.",
  ],
  [
    "vector-addition",
    "Vector Addition",
    "physics",
    9,
    12,
    "Cơ học",
    "Vectơ",
    "simulation",
    20,
    "intermediate",
    ["vectơ", "vector", "tổng hợp vectơ", "thành phần", "component"],
    "Kéo thả các vectơ để cộng chúng, phân tích thành phần theo trục và quan sát độ lớn, hướng của vectơ tổng.",
  ],
  [
    "vector-addition-equations",
    "Vector Addition: Equations",
    "mathematics",
    10,
    12,
    "Vectơ",
    "Phép toán vectơ",
    "simulation",
    20,
    "intermediate",
    ["vectơ", "vector", "phương trình vectơ", "hệ số", "linear combination"],
    "Thực hành các phương trình vectơ với hệ số và so sánh kết quả hình học với đại số.",
  ],
  [
    "under-pressure",
    "Under Pressure",
    "physics",
    8,
    11,
    "Chất lỏng",
    "Áp suất chất lỏng",
    "simulation",
    20,
    "intermediate",
    ["áp suất", "pressure", "áp suất chất lỏng", "fluid pressure", "độ sâu", "khí quyển"],
    "Đo áp suất tại các độ sâu khác nhau trong bể nước với các chất lỏng và gia tốc trọng trường khác nhau.",
  ],
  [
    "density",
    "Density",
    "physics",
    6,
    9,
    "Chất lỏng",
    "Khối lượng riêng",
    "simulation",
    20,
    "beginner",
    ["khối lượng riêng", "density", "thể tích", "khối lượng", "chìm nổi"],
    "Xác định khối lượng riêng của các khối vật liệu bằng cách đo khối lượng và thể tích nước dâng.",
  ],
  [
    "buoyancy",
    "Buoyancy",
    "physics",
    8,
    12,
    "Chất lỏng",
    "Lực đẩy Archimedes",
    "simulation",
    30,
    "intermediate",
    ["lực đẩy archimedes", "buoyancy", "chìm nổi", "khối lượng riêng", "lực đẩy"],
    "Khảo sát lực đẩy Archimedes tác dụng lên vật nhúng trong chất lỏng và điều kiện vật nổi, lơ lửng, chìm.",
  ],
  [
    "buoyancy-basics",
    "Buoyancy: Basics",
    "physics",
    5,
    8,
    "Chất lỏng",
    "Sự nổi",
    "simulation",
    20,
    "beginner",
    ["sự nổi", "buoyancy", "chìm nổi", "khối lượng riêng"],
    "Phiên bản cơ bản giúp học sinh nhận biết vì sao có vật nổi, có vật chìm trong nước.",
  ],
  // ------------------------------- VẬT LÝ – SÓNG, QUANG -------------------------------
  [
    "wave-on-a-string",
    "Wave on a String",
    "physics",
    9,
    12,
    "Sóng",
    "Sóng cơ",
    "simulation",
    20,
    "intermediate",
    ["sóng", "wave", "sóng cơ", "biên độ", "tần số", "sóng dừng", "standing wave"],
    "Tạo sóng trên sợi dây, điều chỉnh biên độ, tần số, độ căng và quan sát phản xạ, sóng dừng.",
  ],
  [
    "waves-intro",
    "Waves Intro",
    "physics",
    6,
    9,
    "Sóng",
    "Sóng nước, âm, ánh sáng",
    "simulation",
    20,
    "beginner",
    ["sóng", "wave", "âm thanh", "sound", "sóng nước", "ánh sáng"],
    "Làm quen với sóng nước, sóng âm và sóng ánh sáng; so sánh biên độ, tần số của các loại sóng.",
  ],
  [
    "wave-interference",
    "Wave Interference",
    "physics",
    10,
    12,
    "Sóng",
    "Giao thoa",
    "simulation",
    30,
    "advanced",
    ["giao thoa", "interference", "nhiễu xạ", "diffraction", "khe young", "double slit"],
    "Quan sát giao thoa và nhiễu xạ của sóng nước, âm, ánh sáng qua hai nguồn kết hợp và khe hẹp.",
  ],
  [
    "normal-modes",
    "Normal Modes",
    "physics",
    11,
    12,
    "Dao động",
    "Dao động chuẩn",
    "simulation",
    30,
    "advanced",
    ["dao động", "normal modes", "hệ lò xo", "tần số riêng"],
    "Khảo sát các mode dao động chuẩn của hệ nhiều vật nối bằng lò xo trong 1D và 2D.",
  ],
  [
    "fourier-making-waves",
    "Fourier: Making Waves",
    "physics",
    11,
    12,
    "Sóng",
    "Phân tích Fourier",
    "simulation",
    30,
    "advanced",
    ["fourier", "sóng", "điều hòa", "harmonic", "tổng hợp dao động"],
    "Tổng hợp các sóng điều hòa để tạo ra dạng sóng phức tạp; giới thiệu trực quan chuỗi Fourier.",
  ],
  [
    "bending-light",
    "Bending Light",
    "physics",
    9,
    12,
    "Quang học",
    "Khúc xạ ánh sáng",
    "simulation",
    30,
    "intermediate",
    ["khúc xạ", "refraction", "phản xạ", "reflection", "chiết suất", "định luật snell", "lăng kính"],
    "Khảo sát khúc xạ và phản xạ ánh sáng qua các môi trường, định luật Snell và phản xạ toàn phần.",
  ],
  [
    "geometric-optics",
    "Geometric Optics",
    "physics",
    10,
    12,
    "Quang học",
    "Thấu kính và gương",
    "simulation",
    30,
    "intermediate",
    ["thấu kính", "lens", "gương", "mirror", "ảnh", "tiêu cự", "quang hình"],
    "Dựng ảnh qua thấu kính và gương, thay đổi tiêu cự, vị trí vật và quan sát ảnh thật, ảnh ảo.",
  ],
  [
    "geometric-optics-basics",
    "Geometric Optics: Basics",
    "physics",
    7,
    10,
    "Quang học",
    "Thấu kính",
    "simulation",
    20,
    "beginner",
    ["thấu kính", "lens", "ảnh", "tia sáng"],
    "Phiên bản cơ bản giới thiệu cách thấu kính tạo ảnh bằng các tia sáng đặc biệt.",
  ],
  [
    "color-vision",
    "Color Vision",
    "physics",
    4,
    9,
    "Quang học",
    "Màu sắc",
    "simulation",
    15,
    "beginner",
    ["màu sắc", "color", "thị giác", "ánh sáng", "bộ lọc màu", "rgb"],
    "Pha trộn ánh sáng đỏ, lục, lam và dùng bộ lọc màu để hiểu mắt người cảm nhận màu sắc như thế nào.",
  ],
  [
    "blackbody-spectrum",
    "Blackbody Spectrum",
    "physics",
    10,
    12,
    "Vật lý hiện đại",
    "Bức xạ vật đen",
    "simulation",
    20,
    "advanced",
    ["bức xạ", "vật đen", "blackbody", "quang phổ", "spectrum", "nhiệt độ"],
    "Quan sát phổ bức xạ của vật đen thay đổi theo nhiệt độ và so sánh với Mặt Trời, bóng đèn, Trái Đất.",
  ],
  [
    "molecules-and-light",
    "Molecules and Light",
    "chemistry",
    6,
    12,
    "Tương tác ánh sáng – vật chất",
    null,
    "simulation",
    15,
    "beginner",
    ["phân tử", "molecule", "ánh sáng", "hồng ngoại", "infrared", "khí nhà kính"],
    "Chiếu các loại ánh sáng (vi sóng, hồng ngoại, khả kiến, tử ngoại) vào phân tử và quan sát phân tử quay, dao động hay bị phân tách.",
  ],
  [
    "models-of-the-hydrogen-atom",
    "Models of the Hydrogen Atom",
    "physics",
    11,
    12,
    "Vật lý hiện đại",
    "Mẫu nguyên tử",
    "simulation",
    30,
    "advanced",
    ["mẫu nguyên tử", "hydrogen atom", "bohr", "rutherford", "quang phổ"],
    "So sánh dự đoán của các mẫu nguyên tử hydro (Dalton, Thomson, Rutherford, Bohr, Schrödinger) với thực nghiệm.",
  ],
  [
    "rutherford-scattering",
    "Rutherford Scattering",
    "physics",
    10,
    12,
    "Vật lý hiện đại",
    "Cấu tạo nguyên tử",
    "simulation",
    20,
    "intermediate",
    ["rutherford", "tán xạ", "hạt nhân", "nucleus", "hạt alpha"],
    "Bắn hạt alpha vào nguyên tử để tái hiện thí nghiệm Rutherford và khám phá sự tồn tại của hạt nhân.",
  ],
  // ------------------------------- NHIỆT – TRẠNG THÁI CHẤT -------------------------------
  [
    "states-of-matter",
    "States of Matter",
    "chemistry",
    8,
    12,
    "Trạng thái của chất",
    "Chuyển thể",
    "simulation",
    30,
    "intermediate",
    ["trạng thái chất", "states of matter", "rắn lỏng khí", "chuyển thể", "nhiệt độ", "phase"],
    "Quan sát chuyển động của phân tử ở thể rắn, lỏng, khí; đun nóng, làm lạnh và nén để thấy sự chuyển thể.",
  ],
  [
    "states-of-matter-basics",
    "States of Matter: Basics",
    "chemistry",
    4,
    8,
    "Trạng thái của chất",
    null,
    "simulation",
    20,
    "beginner",
    ["trạng thái chất", "rắn", "lỏng", "khí", "solid", "liquid", "gas"],
    "Phiên bản cơ bản so sánh cách sắp xếp và chuyển động của các hạt ở ba trạng thái của chất.",
  ],
  [
    "gas-properties",
    "Gas Properties",
    "physics",
    9,
    12,
    "Nhiệt học",
    "Chất khí",
    "simulation",
    30,
    "intermediate",
    ["chất khí", "gas properties", "áp suất", "thể tích", "nhiệt độ", "định luật chất khí"],
    "Bơm các phân tử khí vào bình và khảo sát mối quan hệ giữa áp suất, thể tích, nhiệt độ theo các định luật chất khí.",
  ],
  [
    "gases-intro",
    "Gases Intro",
    "physics",
    7,
    10,
    "Nhiệt học",
    "Chất khí",
    "simulation",
    20,
    "beginner",
    ["chất khí", "gas", "áp suất", "nhiệt độ", "phân tử"],
    "Giới thiệu mô hình hạt của chất khí và mối liên hệ định tính giữa nhiệt độ, áp suất và thể tích.",
  ],
  [
    "diffusion",
    "Diffusion",
    "chemistry",
    7,
    11,
    "Nhiệt học",
    "Khuếch tán",
    "simulation",
    15,
    "beginner",
    ["khuếch tán", "diffusion", "phân tử", "nhiệt độ", "khối lượng"],
    "Quan sát hai loại khí khuếch tán vào nhau và ảnh hưởng của nhiệt độ, khối lượng phân tử đến tốc độ khuếch tán.",
  ],
  [
    "energy-forms-and-changes",
    "Energy Forms and Changes",
    "physics",
    5,
    9,
    "Năng lượng",
    "Chuyển hóa năng lượng",
    "simulation",
    30,
    "beginner",
    ["năng lượng", "energy", "chuyển hóa năng lượng", "nhiệt", "điện năng", "pin mặt trời"],
    "Xây dựng hệ thống chuyển hóa năng lượng từ nguồn đến thiết bị và theo dõi dòng năng lượng qua từng bộ phận.",
  ],
  // ------------------------------- MÔI TRƯỜNG / TRÁI ĐẤT -------------------------------
  [
    "greenhouse-effect",
    "The Greenhouse Effect",
    "environmental-science",
    7,
    12,
    "Khí hậu",
    "Hiệu ứng nhà kính",
    "simulation",
    30,
    "intermediate",
    [
      "hiệu ứng nhà kính",
      "greenhouse effect",
      "biến đổi khí hậu",
      "climate change",
      "khí nhà kính",
      "nhiệt độ",
    ],
    "Khám phá cách khí nhà kính và mây ảnh hưởng đến cân bằng năng lượng và nhiệt độ bề mặt Trái Đất.",
  ],
  // ------------------------------- HÓA HỌC -------------------------------
  [
    "build-an-atom",
    "Build an Atom",
    "chemistry",
    7,
    11,
    "Cấu tạo nguyên tử",
    null,
    "game",
    30,
    "beginner",
    ["nguyên tử", "atom", "proton", "neutron", "electron", "ion", "cấu tạo nguyên tử"],
    "Lắp ráp nguyên tử từ proton, neutron, electron; xác định nguyên tố, điện tích, số khối và chơi trò chơi kiểm tra.",
  ],
  [
    "isotopes-and-atomic-mass",
    "Isotopes and Atomic Mass",
    "chemistry",
    9,
    12,
    "Cấu tạo nguyên tử",
    "Đồng vị",
    "simulation",
    20,
    "intermediate",
    ["đồng vị", "isotope", "nguyên tử khối", "atomic mass", "neutron"],
    "Tạo các đồng vị và tính nguyên tử khối trung bình dựa trên thành phần phần trăm đồng vị trong tự nhiên.",
  ],
  [
    "build-a-molecule",
    "Build a Molecule",
    "chemistry",
    8,
    11,
    "Phân tử",
    "Công thức phân tử",
    "game",
    20,
    "beginner",
    ["phân tử", "molecule", "công thức hóa học", "nguyên tử"],
    "Ghép các nguyên tử thành phân tử và liên hệ công thức hóa học với cấu trúc phân tử.",
  ],
  [
    "molecule-shapes",
    "Molecule Shapes",
    "chemistry",
    10,
    12,
    "Liên kết hóa học",
    "Hình học phân tử",
    "model",
    30,
    "advanced",
    ["hình dạng phân tử", "molecule shapes", "vsepr", "góc liên kết", "cặp electron"],
    "Xây dựng phân tử 3D và khám phá thuyết VSEPR: cặp electron liên kết, không liên kết ảnh hưởng đến góc liên kết.",
  ],
  [
    "molecule-shapes-basics",
    "Molecule Shapes: Basics",
    "chemistry",
    9,
    11,
    "Liên kết hóa học",
    "Hình học phân tử",
    "model",
    20,
    "intermediate",
    ["hình dạng phân tử", "vsepr", "phân tử 3d"],
    "Phiên bản cơ bản giới thiệu hình học phân tử và cách các nhóm electron sắp xếp xa nhau nhất.",
  ],
  [
    "molecule-polarity",
    "Molecule Polarity",
    "chemistry",
    10,
    12,
    "Liên kết hóa học",
    "Độ phân cực",
    "simulation",
    30,
    "advanced",
    ["phân cực", "polarity", "độ âm điện", "electronegativity", "liên kết"],
    "Thay đổi độ âm điện của nguyên tử để thấy liên kết và phân tử trở nên phân cực, đặt phân tử trong điện trường.",
  ],
  [
    "balancing-chemical-equations",
    "Balancing Chemical Equations",
    "chemistry",
    8,
    11,
    "Phản ứng hóa học",
    "Cân bằng phương trình",
    "game",
    20,
    "beginner",
    ["cân bằng phương trình", "balancing chemical equations", "phương trình hóa học", "bảo toàn khối lượng"],
    "Cân bằng phương trình hóa học bằng cách điều chỉnh hệ số, có hình ảnh trực quan và trò chơi nhiều cấp độ.",
  ],
  [
    "reactants-products-and-leftovers",
    "Reactants, Products and Leftovers",
    "chemistry",
    8,
    11,
    "Phản ứng hóa học",
    "Chất phản ứng hết – dư",
    "game",
    30,
    "intermediate",
    ["chất phản ứng", "reactants", "sản phẩm", "products", "chất dư", "limiting reactant", "hóa học lượng"],
    "Tìm hiểu chất phản ứng hết, chất dư qua ví dụ làm bánh sandwich và các phản ứng hóa học thực tế.",
  ],
  [
    "concentration",
    "Concentration",
    "chemistry",
    9,
    12,
    "Dung dịch",
    "Nồng độ",
    "simulation",
    20,
    "intermediate",
    ["nồng độ", "concentration", "dung dịch", "bão hòa", "saturated", "chất tan"],
    "Thêm chất tan, nước hoặc cho bay hơi để khám phá nồng độ dung dịch và trạng thái bão hòa.",
  ],
  [
    "molarity",
    "Molarity",
    "chemistry",
    10,
    12,
    "Dung dịch",
    "Nồng độ mol",
    "simulation",
    20,
    "intermediate",
    ["nồng độ mol", "molarity", "mol", "dung dịch", "thể tích"],
    "Điều chỉnh số mol chất tan và thể tích dung dịch để thấy nồng độ mol thay đổi như thế nào.",
  ],
  [
    "beers-law-lab",
    "Beer's Law Lab",
    "chemistry",
    10,
    12,
    "Dung dịch",
    "Định luật Beer–Lambert",
    "virtual_lab",
    30,
    "advanced",
    ["định luật beer", "beers law", "độ hấp thụ", "absorbance", "quang phổ", "nồng độ"],
    "Dùng máy quang phổ ảo đo độ hấp thụ và độ truyền qua của dung dịch để khám phá định luật Beer–Lambert.",
  ],
  [
    "ph-scale",
    "pH Scale",
    "chemistry",
    9,
    12,
    "Axit – Bazơ",
    "Thang pH",
    "simulation",
    20,
    "intermediate",
    ["ph", "ph scale", "axit", "acid", "bazơ", "base", "nồng độ h+"],
    "Đo pH của các chất quen thuộc, pha loãng dung dịch và liên hệ pH với nồng độ ion H₃O⁺ và OH⁻.",
  ],
  [
    "ph-scale-basics",
    "pH Scale: Basics",
    "chemistry",
    6,
    9,
    "Axit – Bazơ",
    "Thang pH",
    "simulation",
    15,
    "beginner",
    ["ph", "axit", "bazơ", "trung tính", "pha loãng"],
    "Kiểm tra độ axit, bazơ của đồ uống và sản phẩm gia dụng; quan sát pH thay đổi khi pha loãng.",
  ],
  [
    "acid-base-solutions",
    "Acid-Base Solutions",
    "chemistry",
    10,
    12,
    "Axit – Bazơ",
    "Axit mạnh – yếu",
    "simulation",
    30,
    "advanced",
    ["axit mạnh", "axit yếu", "acid base", "điện ly", "độ dẫn điện", "ph"],
    "So sánh axit/bazơ mạnh và yếu ở cấp độ phân tử bằng pH kế, giấy chỉ thị và thiết bị đo độ dẫn điện.",
  ],
  // ------------------------------- SINH HỌC -------------------------------
  [
    "natural-selection",
    "Natural Selection",
    "biology",
    7,
    12,
    "Tiến hóa",
    "Chọn lọc tự nhiên",
    "simulation",
    30,
    "intermediate",
    ["chọn lọc tự nhiên", "natural selection", "tiến hóa", "evolution", "đột biến", "mutation", "quần thể"],
    "Quan sát quần thể thỏ thay đổi qua các thế hệ khi môi trường, thú săn mồi và đột biến tác động đến sự sống sót.",
  ],
  [
    "gene-expression-essentials",
    "Gene Expression Essentials",
    "biology",
    9,
    12,
    "Di truyền",
    "Biểu hiện gen",
    "simulation",
    30,
    "advanced",
    ["biểu hiện gen", "gene expression", "phiên mã", "transcription", "dịch mã", "protein", "mrna"],
    "Mô phỏng quá trình phiên mã và dịch mã tạo protein, yếu tố điều hòa và sự phân hủy mRNA trong tế bào.",
  ],
  [
    "neuron",
    "Neuron",
    "biology",
    9,
    12,
    "Sinh lý người",
    "Hệ thần kinh",
    "simulation",
    20,
    "advanced",
    ["tế bào thần kinh", "neuron", "điện thế hoạt động", "action potential", "kênh ion"],
    "Kích thích tế bào thần kinh và quan sát điện thế hoạt động lan truyền cùng dòng ion qua kênh màng.",
  ],
  // ------------------------------- TOÁN HỌC -------------------------------
  [
    "area-model-multiplication",
    "Area Model Multiplication",
    "mathematics",
    3,
    6,
    "Số học",
    "Phép nhân",
    "simulation",
    20,
    "beginner",
    ["phép nhân", "multiplication", "mô hình diện tích", "area model", "phân tích số"],
    "Dùng mô hình diện tích hình chữ nhật để hiểu phép nhân nhiều chữ số và tính chất phân phối.",
  ],
  [
    "area-model-introduction",
    "Area Model Introduction",
    "mathematics",
    2,
    4,
    "Số học",
    "Phép nhân",
    "simulation",
    15,
    "beginner",
    ["phép nhân", "area model", "diện tích", "bảng cửu chương"],
    "Giới thiệu phép nhân qua việc chia hình chữ nhật thành các phần có diện tích dễ tính.",
  ],
  [
    "area-model-decimals",
    "Area Model Decimals",
    "mathematics",
    5,
    7,
    "Số học",
    "Số thập phân",
    "simulation",
    20,
    "intermediate",
    ["số thập phân", "decimals", "phép nhân", "area model"],
    "Mở rộng mô hình diện tích cho phép nhân số thập phân.",
  ],
  [
    "area-model-algebra",
    "Area Model Algebra",
    "mathematics",
    7,
    9,
    "Đại số",
    "Nhân đa thức",
    "simulation",
    20,
    "intermediate",
    ["đa thức", "polynomial", "nhân đa thức", "area model", "đại số"],
    "Biểu diễn phép nhân đa thức bằng mô hình diện tích, nối liền số học và đại số.",
  ],
  [
    "area-builder",
    "Area Builder",
    "mathematics",
    3,
    6,
    "Hình học",
    "Diện tích và chu vi",
    "game",
    20,
    "beginner",
    ["diện tích", "area", "chu vi", "perimeter", "hình học"],
    "Xếp các ô vuông để tạo hình, so sánh diện tích và chu vi; kèm trò chơi thử thách.",
  ],
  [
    "arithmetic",
    "Arithmetic",
    "mathematics",
    2,
    5,
    "Số học",
    "Bảng cửu chương",
    "game",
    15,
    "beginner",
    ["số học", "arithmetic", "phép nhân", "phép chia", "bảng cửu chương"],
    "Luyện tập phép nhân, phân tích thừa số và phép chia qua trò chơi tính nhanh.",
  ],
  [
    "make-a-ten",
    "Make a Ten",
    "mathematics",
    1,
    2,
    "Số học",
    "Phép cộng",
    "game",
    15,
    "beginner",
    ["phép cộng", "addition", "làm tròn chục", "tính nhẩm", "số đếm"],
    'Học chiến lược "gộp đủ chục" để cộng nhẩm nhanh qua các thẻ số trực quan.',
  ],
  [
    "number-line-integers",
    "Number Line: Integers",
    "mathematics",
    6,
    7,
    "Số học",
    "Số nguyên",
    "simulation",
    15,
    "beginner",
    ["số nguyên", "integer", "trục số", "number line", "số âm"],
    "Biểu diễn số nguyên trên trục số, so sánh và tìm giá trị tuyệt đối trong các bối cảnh thực tế.",
  ],
  [
    "number-line-operations",
    "Number Line: Operations",
    "mathematics",
    6,
    8,
    "Số học",
    "Phép tính số nguyên",
    "simulation",
    15,
    "beginner",
    ["trục số", "number line", "cộng trừ số nguyên", "số âm"],
    "Thực hiện phép cộng, trừ số nguyên bằng các bước nhảy trên trục số.",
  ],
  [
    "number-line-distance",
    "Number Line: Distance",
    "mathematics",
    6,
    8,
    "Số học",
    "Khoảng cách",
    "simulation",
    15,
    "beginner",
    ["trục số", "khoảng cách", "giá trị tuyệt đối", "absolute value"],
    "Khám phá khoảng cách giữa hai điểm trên trục số và mối liên hệ với giá trị tuyệt đối.",
  ],
  [
    "fractions-intro",
    "Fractions: Intro",
    "mathematics",
    3,
    5,
    "Phân số",
    null,
    "simulation",
    20,
    "beginner",
    ["phân số", "fraction", "tử số", "mẫu số"],
    "Biểu diễn phân số bằng hình tròn, thanh, cốc nước và trên trục số.",
  ],
  [
    "fractions-equality",
    "Fractions: Equality",
    "mathematics",
    3,
    5,
    "Phân số",
    "Phân số bằng nhau",
    "simulation",
    20,
    "beginner",
    ["phân số bằng nhau", "equivalent fractions", "phân số"],
    "Tìm các phân số bằng nhau bằng cách chia nhỏ hoặc gộp các phần của một hình.",
  ],
  [
    "fractions-mixed-numbers",
    "Fractions: Mixed Numbers",
    "mathematics",
    4,
    6,
    "Phân số",
    "Hỗn số",
    "simulation",
    20,
    "beginner",
    ["hỗn số", "mixed numbers", "phân số lớn hơn 1"],
    "Biểu diễn hỗn số và phân số lớn hơn 1 bằng nhiều mô hình trực quan.",
  ],
  [
    "build-a-fraction",
    "Build a Fraction",
    "mathematics",
    3,
    6,
    "Phân số",
    null,
    "game",
    20,
    "beginner",
    ["phân số", "build a fraction", "trò chơi"],
    "Ghép các mảnh hình và số để tạo phân số theo yêu cầu qua các cấp độ trò chơi.",
  ],
  [
    "fraction-matcher",
    "Fraction Matcher",
    "mathematics",
    3,
    6,
    "Phân số",
    "So sánh phân số",
    "game",
    15,
    "beginner",
    ["phân số", "so sánh phân số", "fraction matcher", "trò chơi"],
    "Nối các phân số bằng nhau được biểu diễn bằng hình và số trong trò chơi ghép cặp.",
  ],
  [
    "equality-explorer",
    "Equality Explorer",
    "mathematics",
    6,
    9,
    "Đại số",
    "Phương trình",
    "simulation",
    30,
    "intermediate",
    ["phương trình", "equation", "cân bằng", "ẩn số", "đại số"],
    "Dùng chiếc cân thăng bằng để hiểu và giải phương trình bậc nhất một ẩn.",
  ],
  [
    "equality-explorer-basics",
    "Equality Explorer: Basics",
    "mathematics",
    4,
    7,
    "Đại số",
    "Đẳng thức",
    "simulation",
    20,
    "beginner",
    ["đẳng thức", "cân bằng", "phương trình", "equality"],
    "Làm quen khái niệm đẳng thức bằng cách giữ cho chiếc cân luôn thăng bằng.",
  ],
  [
    "expression-exchange",
    "Expression Exchange",
    "mathematics",
    6,
    9,
    "Đại số",
    "Biểu thức",
    "game",
    20,
    "intermediate",
    ["biểu thức", "expression", "rút gọn", "đơn thức đồng dạng"],
    "Rút gọn biểu thức đại số bằng cách gộp các hạng tử đồng dạng dưới dạng đồng xu trực quan.",
  ],
  [
    "graphing-lines",
    "Graphing Lines",
    "mathematics",
    8,
    10,
    "Hàm số",
    "Đường thẳng",
    "simulation",
    30,
    "intermediate",
    ["đường thẳng", "graphing lines", "hệ số góc", "slope", "phương trình đường thẳng"],
    "Khám phá hệ số góc và phương trình đường thẳng qua các dạng điểm – hệ số góc và hệ số góc – tung độ gốc.",
  ],
  [
    "graphing-slope-intercept",
    "Graphing Slope-Intercept",
    "mathematics",
    8,
    10,
    "Hàm số",
    "Đường thẳng y = ax + b",
    "simulation",
    20,
    "intermediate",
    ["hàm số bậc nhất", "slope intercept", "y = ax + b", "đồ thị"],
    "Vẽ đồ thị hàm số bậc nhất và quan sát ảnh hưởng của hệ số góc, tung độ gốc.",
  ],
  [
    "graphing-quadratics",
    "Graphing Quadratics",
    "mathematics",
    9,
    11,
    "Hàm số",
    "Hàm số bậc hai",
    "simulation",
    30,
    "intermediate",
    ["hàm số bậc hai", "quadratic", "parabol", "parabola", "đỉnh", "nghiệm"],
    "Khám phá đồ thị hàm số bậc hai: đỉnh, trục đối xứng, nghiệm và tiêu điểm của parabol.",
  ],
  [
    "function-builder",
    "Function Builder",
    "mathematics",
    7,
    10,
    "Hàm số",
    "Hàm hợp",
    "simulation",
    30,
    "intermediate",
    ["hàm số", "function", "hàm hợp", "biến đổi", "đầu vào đầu ra"],
    'Xếp chuỗi các "cỗ máy hàm" để biến đổi đầu vào, khám phá hàm hợp và hàm ngược.',
  ],
  [
    "function-builder-basics",
    "Function Builder: Basics",
    "mathematics",
    3,
    6,
    "Hàm số",
    "Quy luật",
    "simulation",
    20,
    "beginner",
    ["quy luật", "pattern", "hàm số", "đầu vào đầu ra"],
    "Tìm quy luật biến đổi hình dạng và con số qua các cỗ máy hàm đơn giản.",
  ],
  [
    "unit-rates",
    "Unit Rates",
    "mathematics",
    5,
    7,
    "Tỉ số",
    "Đơn giá",
    "simulation",
    20,
    "beginner",
    ["đơn giá", "unit rate", "tỉ số", "ratio", "mua sắm"],
    "Tính đơn giá và so sánh tỉ số qua các tình huống mua sắm và cuộc đua.",
  ],
  [
    "ratio-and-proportion",
    "Ratio and Proportion",
    "mathematics",
    5,
    8,
    "Tỉ số",
    "Tỉ lệ thức",
    "simulation",
    20,
    "beginner",
    ["tỉ số", "ratio", "tỉ lệ", "proportion"],
    "Điều khiển hai bàn tay để giữ đúng tỉ số, cảm nhận trực quan về tỉ lệ thức.",
  ],
  [
    "proportion-playground",
    "Proportion Playground",
    "mathematics",
    5,
    8,
    "Tỉ số",
    "Tỉ lệ",
    "simulation",
    20,
    "beginner",
    ["tỉ lệ", "proportion", "tỉ số", "vòng cổ", "pha màu"],
    "Khám phá tỉ lệ qua việc làm vòng cổ, pha màu sơn, chia táo và bóng đổ.",
  ],
  [
    "plinko-probability",
    "Plinko Probability",
    "mathematics",
    7,
    12,
    "Xác suất – Thống kê",
    "Phân phối nhị thức",
    "simulation",
    20,
    "intermediate",
    ["xác suất", "probability", "phân phối nhị thức", "binomial", "histogram"],
    "Thả các viên bi qua bảng Plinko để khám phá xác suất và phân phối nhị thức.",
  ],
  [
    "least-squares-regression",
    "Least-Squares Regression",
    "mathematics",
    10,
    12,
    "Xác suất – Thống kê",
    "Hồi quy tuyến tính",
    "simulation",
    30,
    "advanced",
    ["hồi quy", "regression", "bình phương tối thiểu", "least squares", "tương quan"],
    "Tìm đường thẳng khớp dữ liệu tốt nhất và hiểu ý nghĩa tổng bình phương sai số, hệ số tương quan.",
  ],
  [
    "curve-fitting",
    "Curve Fitting",
    "mathematics",
    11,
    12,
    "Xác suất – Thống kê",
    "Khớp đường cong",
    "simulation",
    30,
    "advanced",
    ["khớp đường cong", "curve fitting", "đa thức", "chi bình phương"],
    "Khớp các đa thức bậc 1 đến bậc 3 với dữ liệu có sai số và đánh giá độ phù hợp.",
  ],
  [
    "center-and-variability",
    "Center and Variability",
    "mathematics",
    6,
    8,
    "Xác suất – Thống kê",
    "Số trung bình, trung vị",
    "simulation",
    30,
    "intermediate",
    ["trung bình", "mean", "trung vị", "median", "độ phân tán", "thống kê"],
    "Thu thập dữ liệu từ các cú đá bóng để tìm số trung bình, trung vị, khoảng biến thiên và độ lệch.",
  ],
  [
    "mean-share-and-balance",
    "Mean: Share and Balance",
    "mathematics",
    5,
    7,
    "Xác suất – Thống kê",
    "Số trung bình",
    "simulation",
    15,
    "beginner",
    ["trung bình cộng", "mean", "chia đều", "thống kê"],
    "Hiểu số trung bình cộng như cách chia đều và điểm cân bằng của dữ liệu.",
  ],
  [
    "number-play",
    "Number Play",
    "mathematics",
    1,
    2,
    "Số học",
    "Đếm số",
    "simulation",
    15,
    "beginner",
    ["đếm số", "counting", "số đến 20", "mầm non"],
    "Đếm, biểu diễn và so sánh các số đến 20 bằng nhiều cách khác nhau.",
  ],
  [
    "number-compare",
    "Number Compare",
    "mathematics",
    1,
    2,
    "Số học",
    "So sánh số",
    "simulation",
    15,
    "beginner",
    ["so sánh số", "lớn hơn", "bé hơn", "number compare"],
    "So sánh các số đến 20 bằng mô hình trực quan và trục số.",
  ],
  [
    "trig-tour",
    "Trig Tour",
    "mathematics",
    10,
    12,
    "Lượng giác",
    "Đường tròn lượng giác",
    "simulation",
    20,
    "intermediate",
    ["lượng giác", "trigonometry", "sin", "cos", "tan", "đường tròn lượng giác"],
    "Khám phá sin, cos, tan trên đường tròn lượng giác và đồ thị tương ứng.",
  ],
  [
    "calculus-grapher",
    "Calculus Grapher",
    "mathematics",
    11,
    12,
    "Giải tích",
    "Đạo hàm và tích phân",
    "simulation",
    30,
    "advanced",
    ["đạo hàm", "derivative", "tích phân", "integral", "giải tích", "calculus"],
    "Vẽ hàm số và quan sát đồng thời đồ thị đạo hàm, tích phân để hiểu mối liên hệ giữa chúng.",
  ],
  [
    "quadrilateral",
    "Quadrilateral",
    "mathematics",
    5,
    8,
    "Hình học",
    "Tứ giác",
    "simulation",
    20,
    "beginner",
    ["tứ giác", "quadrilateral", "hình bình hành", "hình thoi", "hình hình học"],
    "Kéo các đỉnh để khám phá tính chất các loại tứ giác: hình thang, hình bình hành, hình thoi, hình vuông.",
  ],
];
