-- =============================================================================
-- Dữ liệu tham chiếu bắt buộc: môn học, khối lớp, từ đồng nghĩa tìm kiếm song ngữ
-- =============================================================================

insert into public.subjects (slug, name, name_vi, icon, color, aliases, sort_order) values
  ('physics', 'Physics', 'Vật lý', 'atom', '#2563eb',
    array['vat ly', 'vat li', 'ly', 'physics', 'physical science'], 10),
  ('chemistry', 'Chemistry', 'Hóa học', 'flask-conical', '#0891b2',
    array['hoa', 'hoa hoc', 'chemistry', 'chem'], 20),
  ('biology', 'Biology', 'Sinh học', 'dna', '#16a34a',
    array['sinh', 'sinh hoc', 'biology', 'bio', 'life science'], 30),
  ('mathematics', 'Mathematics', 'Toán học', 'sigma', '#7c3aed',
    array['toan', 'toan hoc', 'math', 'maths', 'mathematics'], 40),
  ('earth-science', 'Earth Science', 'Khoa học Trái đất', 'globe', '#b45309',
    array['khoa hoc trai dat', 'dia ly', 'dia li', 'earth science', 'geoscience', 'astronomy', 'thien van', 'earth and space'], 50),
  ('environmental-science', 'Environmental Science', 'Khoa học Môi trường', 'leaf', '#65a30d',
    array['moi truong', 'khoa hoc moi truong', 'environmental science', 'environment', 'ecology', 'sinh thai'], 60),
  ('computer-science', 'Computer Science', 'Tin học', 'cpu', '#475569',
    array['tin hoc', 'tin', 'computer science', 'cs', 'coding', 'lap trinh', 'programming'], 70),
  ('stem', 'STEM', 'STEM', 'rocket', '#ea580c',
    array['stem', 'steam', 'engineering', 'ky thuat', 'cong nghe', 'technology', 'khoa hoc tu nhien', 'science'], 80)
on conflict (slug) do update set
  name = excluded.name, name_vi = excluded.name_vi, icon = excluded.icon, color = excluded.color,
  aliases = excluded.aliases, sort_order = excluded.sort_order;

insert into public.grades (id, name, name_vi, education_level, age_min, age_max)
select g, 'Grade ' || g, 'Lớp ' || g,
       case when g <= 5 then 'primary' when g <= 9 then 'lower_secondary' else 'upper_secondary' end,
       g + 5, g + 6
from generate_series(1, 12) g
on conflict (id) do update set
  name = excluded.name, name_vi = excluded.name_vi, education_level = excluded.education_level,
  age_min = excluded.age_min, age_max = excluded.age_max;

-- Thuật ngữ tiếng Việt (không dấu) → từ khoá tiếng Anh tương ứng.
insert into public.search_synonyms (term, expansions) values
  ('dinh luat ohm', array['ohm', 'ohms law', 'resistance', 'voltage', 'current', 'circuit']),
  ('ohm', array['ohms law', 'resistance', 'circuit']),
  ('mach dien', array['circuit', 'circuit construction', 'electric circuit']),
  ('dien tro', array['resistance', 'resistor', 'ohm']),
  ('hieu dien the', array['voltage', 'potential difference']),
  ('cuong do dong dien', array['current', 'ammeter']),
  ('dong dien', array['current', 'electric current', 'circuit']),
  ('dong dien xoay chieu', array['alternating current', 'ac circuit']),
  ('tu dien', array['capacitor', 'capacitance']),
  ('dien truong', array['electric field', 'charges and fields']),
  ('tinh dien', array['static electricity', 'charge', 'balloons']),
  ('dien tich', array['charge', 'coulomb']),
  ('dinh luat coulomb', array['coulombs law', 'electric force', 'charge']),
  ('tu truong', array['magnetic field', 'magnet']),
  ('nam cham', array['magnet', 'magnetic field']),
  ('cam ung dien tu', array['electromagnetic induction', 'faraday']),
  ('dinh luat newton', array['newton', 'force', 'motion', 'acceleration']),
  ('luc', array['force', 'forces and motion']),
  ('tong hop luc', array['net force', 'vector addition']),
  ('chuyen dong', array['motion', 'velocity', 'acceleration']),
  ('van toc', array['velocity', 'speed']),
  ('gia toc', array['acceleration']),
  ('ma sat', array['friction']),
  ('trong luc', array['gravity', 'weight']),
  ('hap dan', array['gravity', 'gravitational force', 'gravity force']),
  ('quy dao', array['orbit', 'orbits']),
  ('he mat troi', array['solar system', 'planet', 'orbit']),
  ('kepler', array['keplers laws', 'orbit']),
  ('nem xien', array['projectile motion', 'projectile']),
  ('chuyen dong nem', array['projectile motion', 'projectile']),
  ('con lac', array['pendulum']),
  ('lo xo', array['spring', 'hookes law', 'masses and springs']),
  ('dinh luat hooke', array['hookes law', 'spring']),
  ('nang luong', array['energy']),
  ('co nang', array['mechanical energy', 'kinetic energy', 'potential energy', 'energy skate park']),
  ('dong nang', array['kinetic energy']),
  ('the nang', array['potential energy']),
  ('bao toan nang luong', array['energy conservation', 'energy skate park']),
  ('dong luong', array['momentum', 'collision']),
  ('va cham', array['collision', 'momentum']),
  ('can bang', array['balance', 'balancing act', 'torque']),
  ('don bay', array['lever', 'balancing act', 'torque']),
  ('momen luc', array['torque']),
  ('song', array['wave', 'waves']),
  ('song co', array['wave on a string', 'wave']),
  ('giao thoa', array['interference', 'wave interference']),
  ('am thanh', array['sound', 'wave']),
  ('anh sang', array['light']),
  ('khuc xa', array['refraction', 'bending light']),
  ('phan xa', array['reflection']),
  ('thau kinh', array['lens', 'geometric optics']),
  ('quang hoc', array['optics', 'light']),
  ('mau sac', array['color', 'color vision']),
  ('quang pho', array['spectrum', 'blackbody']),
  ('ap suat', array['pressure']),
  ('luc day archimedes', array['buoyancy']),
  ('luc day', array['buoyancy']),
  ('khoi luong rieng', array['density']),
  ('ap suat chat long', array['fluid pressure', 'under pressure']),
  ('nhiet do', array['temperature', 'heat']),
  ('nhiet', array['heat', 'thermal energy']),
  ('chat khi', array['gas', 'gas properties']),
  ('trang thai chat', array['states of matter', 'solid', 'liquid', 'gas']),
  ('khuech tan', array['diffusion']),
  ('nguyen tu', array['atom', 'build an atom']),
  ('cau tao nguyen tu', array['atom', 'atomic structure', 'build an atom']),
  ('mau nguyen tu', array['atomic model', 'hydrogen atom', 'rutherford']),
  ('dong vi', array['isotope', 'atomic mass']),
  ('hat nhan', array['nucleus']),
  ('phan tu', array['molecule']),
  ('hinh dang phan tu', array['molecule shapes', 'vsepr']),
  ('phan cuc', array['polarity', 'molecule polarity']),
  ('lien ket hoa hoc', array['chemical bond', 'bonding']),
  ('phuong trinh hoa hoc', array['chemical equation', 'balancing chemical equations']),
  ('can bang phuong trinh', array['balancing chemical equations']),
  ('phan ung hoa hoc', array['chemical reaction', 'reactants', 'products']),
  ('chat phan ung', array['reactants', 'limiting reactant']),
  ('axit', array['acid', 'acid base']),
  ('bazo', array['base', 'acid base']),
  ('ph', array['ph scale', 'acid', 'base']),
  ('nong do', array['concentration', 'molarity']),
  ('dung dich', array['solution', 'concentration']),
  ('mol', array['mole', 'molarity', 'stoichiometry']),
  ('nong do mol', array['molarity']),
  ('chuan do', array['titration']),
  ('hap thu', array['absorbance', 'beers law']),
  ('hieu ung nha kinh', array['greenhouse effect', 'climate']),
  ('bien doi khi hau', array['climate change', 'greenhouse effect']),
  ('chon loc tu nhien', array['natural selection', 'evolution']),
  ('tien hoa', array['evolution', 'natural selection']),
  ('di truyen', array['genetics', 'gene']),
  ('gen', array['gene', 'gene expression']),
  ('bieu hien gen', array['gene expression']),
  ('adn', array['dna', 'gene']),
  ('te bao', array['cell']),
  ('than kinh', array['neuron', 'nerve']),
  ('quang hop', array['photosynthesis']),
  ('ho hap', array['respiration']),
  ('phan so', array['fraction', 'fractions']),
  ('phep nhan', array['multiplication', 'area model']),
  ('phep cong', array['addition', 'arithmetic']),
  ('so hoc', array['arithmetic']),
  ('so nguyen', array['integer', 'number line']),
  ('truc so', array['number line']),
  ('ham so', array['function', 'graph']),
  ('do thi', array['graph', 'graphing']),
  ('phuong trinh', array['equation', 'equality']),
  ('duong thang', array['line', 'graphing lines', 'slope']),
  ('he so goc', array['slope']),
  ('ham bac hai', array['quadratic', 'parabola']),
  ('parabol', array['parabola', 'quadratic']),
  ('luong giac', array['trigonometry', 'trig']),
  ('xac suat', array['probability']),
  ('thong ke', array['statistics', 'mean', 'data']),
  ('ti le', array['ratio', 'proportion']),
  ('ty le', array['ratio', 'proportion']),
  ('hinh hoc', array['geometry']),
  ('dien tich hinh', array['area']),
  ('the tich', array['volume']),
  ('tu giac', array['quadrilateral']),
  ('vecto', array['vector']),
  ('dao ham', array['derivative', 'calculus']),
  ('tich phan', array['integral', 'calculus']),
  ('hoi quy', array['regression', 'least squares']),
  ('lap trinh', array['programming', 'coding', 'blocks']),
  ('thien van', array['astronomy', 'sky', 'planetarium']),
  ('bau troi', array['sky', 'planetarium']),
  ('trai dat', array['earth']),
  ('mat trang', array['moon']),
  ('khi quyen', array['atmosphere']),
  ('dong dat', array['earthquake']),
  ('nui lua', array['volcano'])
on conflict (term) do update set expansions = excluded.expansions;
